#!/usr/bin/env python
# -*- coding: UTF-8 -*-
"""Project Euler: 0045

https://projecteuler.net/problem=45

Triangular, pentagonal, and hexagonal

Triangle, pentagonal, and hexagonal numbers are generated by the following
formulae:

Triangle    T(n) = n(n+1)/2   1, 3, 6, 10, 15, ...
Pentagonal  P(n) = n(3n−1)/2  1, 5, 12, 22, 35, ...
Hexagonal   H(n) = n(2n−1)    1, 6, 15, 28, 45, ...

It can be verified that T(285) = P(165) = H(143) = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

PROBLEM = 45
SOLVED = True
SPEED = 0.08
TAGS = ['triangluar', 'pentagonal', 'hexagonal']


def triangle(number):
    """Calculate the triangular value of number."""
    return number * (number + 1) / 2


def pentagon(number):
    """Calculate the pentagonal value of number."""
    return number * (3*number - 1) / 2


def hexagon(number):
    """Calculate the hexagonal value of number."""
    return number * (2*number - 1)


def main():
    """Solve problem."""
    print 'Project Euler: %04d' % PROBLEM
    numbers = [2, 2, 144]
    while True:
        hexa = hexagon(numbers[2])
        while pentagon(numbers[1]) < hexa:
            numbers[1] += 1
        while triangle(numbers[0]) < hexa:
            numbers[0] += 1
        if hexa == pentagon(numbers[1]) == triangle(numbers[0]):
            print '%d == T(%d) == P(%d) == H(%d)' % tuple([hexa] + numbers)
            break
        numbers[2] += 1
        if numbers[2] == 144:
            break


if __name__ == '__main__':
    main()
